### ISSUE TITLE
Performance on other datasets

### ISSUE THREAD

**Issue by heiyuxiaokai** [HamPerdredes/SOOD#12]
Codes of SOOD work well on Dotav1.5. But its effectiveness is not obvious on Dotav1.0, compared with DenseTeacher. Could authors give me some suggestions? (Perhaps the sampling ratio or other parameters)

**Comment by HamPerdredes** [comment]
One of the main differences between DOTA-1.0 and DOTA-1.5 is that DOTA-1.5 contains fine grained annotations for small/tiny objects and the overall annotation quality is better. In this case, here is a possible cause: although some small/tiny objects are detected by the teacher model for global constraint, they are actually "NOISE" for the evaluation. Therefore, the global consistency loss could be less effective. 
To tackle this problem in a simple way, you could try to adjust some hyper-parameters, such as sample ratio. Besides, you can try to sample the top-k results in each region rather than in a random manner.
I am not sure if above suggestions can be helpful, but I believe you can try to solve the mentioned cause. 
Hope to hear your feedback.

**Comment by heiyuxiaokai** [comment]
Thanks for your kind reply. I have tried SOOD on Dotav1.0 with the sample ratio of 0.25, 0.5 and 1.0. From the results of mAP, there is not obviou variations. **The sample ratio seems not to be the key factor causing this gap.** I'll try the other aforementioned factor.
