### ISSUE TITLE
when i set the samples_per_gpu=6,     workers_per_gpu=6 and then i encountered the error:AssertionError: Only support batch size equals to 1 for now

### ISSUE THREAD

**Issue by 1shenhui** [HamPerdredes/SOOD#20]
this is my comment:CUDA_VISIBLE_DEVICES=0 nohup python train.py /home/shenhui/semi-objetc-detection/SOOD-main/configs/ssad_fcos/sood_fcos_dota15_10per.py --work-dir /hdc/workspace_sh/work_dirs/semi_object_detection/SOOD/single_gpu_reproduce >single_gpu_reproduce.txt 2>&1 &
and the only change is the evaluation: evaluation = dict(type="SubModulesEvalHook", interval=3200, metric='mAP',
                  save_best='mAP')
i used the SubModulesEvalHook, and the author uses the SubModulesDistEvalHook
 
how can i solve the problem

**Comment by HamPerdredes** [comment]
The semi-supervised part in the released code treats unlabeled data with batch size equals to 1 by default (I used the hard code). In order to fix this problem, please change the code in semi-supervised loss manually, especially the Global Consistency (GC) part. Please consider to use a "for" loop to calculate each example's GC loss, and then sum them together.
